name: flutter_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # UI适配插件
  flutter_screenutil: ^0.7.0
  # 弹出框组件
  fluttertoast: ^3.1.3
  # 使用svg插件
  flutter_svg: ^0.15.0
  # 网络请求库
  dio: ^3.0.8
  # 轮播图
  flutter_swiper: ^1.1.6
  # JSON解析
  # json_annotation: ^3.0.1
  # 拨打电话
  # url_launcher: ^5.4.1
  get_it: ^3.1.0
  # 定位
  amap_location: ^0.2.0
#   amap_location_fluttify: ^0.8.5+107df19
  # 图片获取
  image_picker: ^0.6.2+3
  # 扫码
  barcode_scan: ^1.0.0
  # 微信登录
  fluwx: ^1.2.1+1
  # 存储
  shared_preferences: ^0.5.6
  # webview
  flutter_webview_plugin: ^0.3.10+1
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
   - images/appBar/heigshouye_9_12.9@2x.png
   - images/appBar/hongshouye_9_12.9@2x.png
   - images/appBar/heihuiyuan_9_12.9@2x.png
   - images/appBar/honghuiyuan_9_12.9@2x.png
   - images/appBar/heishangpin_9_12.9@2x.png
   - images/appBar/hongishangpin_9_12.9@2x.png
   - images/appBar/heiyuyue_9_12.9@2x.png
   - images/appBar/hongyuyue_9_12.9@2x.png
   # 首页图片 
   - images/index/shouyejinsedianhuahao_9_12.9@2x.png
   - images/index/shouyejinsedingwe_9_12.9@2x.png
   - images/index/sousuo_9_12.9@2x.png
   - images/index/shouyejingpin_9_12.9@2x.png
   - images/index/shouyexinpinshangjia_9_12.9@2x.png
   - images/index/xiangqingdianhua_9_12.9@2x.png
   - images/index/xiangqingdingwei_9_12.9@2x.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
